### ISSUE TITLE
Request: can add a global dispatcher?

### ISSUE THREAD

**Issue by kayazinc** [soundstep/soma-events#1]
Can you add a global dispatcher in the library, which can be shared among multiple components?

**Comment by soundstep** [comment]
It can be used as a global dispatcher, I'm not sure what you mean.
It has been used that way in the somajs framework: http://somajs.github.io/somajs/#/

**Comment by kayazinc** [comment]
Thanks @soundstep, let me elaborate further:

There are two components:  _search-selector_ and _news-content_.
1.  User select a object in the _search-selector_ component and the object will be dispatched.
2.  The _news-content_ component listens to event and generate the news content based on the object.

So in the _search-selector_ implementation,

``` javascript
var dispatcher = new soma.EventDispatcher();
var event = new soma.Event('keywordChanged', {key: someObject});
dispatcher.dispatchEvent(event);
```

And in the _new-content_ implementation,

``` javascript
var dispatcher = new soma.EventDispatcher();
dispatcher.addEventListener('keywordChanged', this.handler.bind(this));
```

But because the dispatchers is two different instances, the event is not received.

So I was thinking if its possible to have a static global dispatcher for both components?  

What is the best way of doing so while decoupling the two components?  Please advise me, thanks!

**Comment by soundstep** [comment]
You need to create only one dispatcher, that will be your "global" dispatcher.

``` javascript
var dispatcher = new soma.EventDispatcher();

function SearchSelector(dispatcher) {
    dispatcher.dispatchEvent(new soma.Event('keywordChanged', {key: someObject}));
}

function NewsContent(dispatcher) {
    dispatcher.dispatchEvent(new soma.Event('anotherEvent'));
}

var search = new SearchSelector(dispatcher);
var news = new NewsContent(dispatcher);
```

Have a look at soma.js, it is small and simple, have that small structure setup for you (with a global dispatcher).

http://somajs.github.io/somajs/

**Comment by kayazinc** [comment]
Ok thanks @soundstep, I got it.
